name: Tests and Package OSX

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-10.15
    env:
      QBDI_PLATFORM: 'osx'
      QBDI_ARCH: 'X86_64'
      MACOSX_DEPLOYMENT_TARGET: '10.14'
    steps:
      - name: Install system dependencies
        run: |
          brew install cmake ninja ccache
          python3 -m pip install --upgrade pip setuptools wheel
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache ccache
        uses: actions/cache@v2
        id: cache-ccache
        with:
          path: |
            ~/.ccache
          key: ccache-osx-X86_64-${{ hashFiles('.github/workflows/ccache.conf') }}
      - if: steps.cache-ccache.outputs.cache-hit != 'true'
        run: |
          mkdir ~/.ccache
          cp .github/workflows/ccache.conf ~/.ccache/ccache.conf
      - name: Cache llvm
        uses: actions/cache@v2
        id: cache-llvm
        with:
          path: |
            deps/llvm/osx-X86_64/include
            deps/llvm/osx-X86_64/lib
          key: llvm-${{ runner.os }}-osx-X86_64-${{ hashFiles('deps/llvm/build.py') }}-${{ env.MACOSX_DEPLOYMENT_TARGET }}
      - run: mkdir -p build
      - name: build llvm
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          python3 ./deps/llvm/build.py prepare ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py build   ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py package ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py clean   ${QBDI_PLATFORM}-${QBDI_ARCH}
      - name: build QBDI
        working-directory: ./build
        run: |
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CROSSCOMPILING=FALSE -DQBDI_PLATFORM=${QBDI_PLATFORM} -DQBDI_ARCH=${QBDI_ARCH} -DQBDI_TOOLS_VALIDATOR=ON -DQBDI_EXAMPLES=ON
          ninja 
          cpack
      - name: test QBDI
        working-directory: ./build/test
        run: |
          ./QBDITest
      - name: Export package
        uses: actions/upload-artifact@v2
        with:
          name: package OSX X86_64
          path: build/QBDI-*.pkg




