name: PyQBDI OSX package

on:
  push:
    branches:
      - main
      - dev-next
  workflow_dispatch:

jobs:
  build-llvm:
    runs-on: macos-10.15
    env:
      QBDI_PLATFORM: 'osx'
      QBDI_ARCH: 'X86_64'
      MACOSX_DEPLOYMENT_TARGET: '10.14'
    steps:
      - name: Install system dependencies
        run: |
          brew install cmake ninja ccache
          python3 -m pip install --upgrade pip setuptools wheel
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache ccache
        uses: actions/cache@v2
        id: cache-ccache
        with:
          path: |
            ~/.ccache
          key: ccache-osx-X86_64-${{ hashFiles('.github/workflows/ccache.conf') }}
      - if: steps.cache-ccache.outputs.cache-hit != 'true'
        run: |
          mkdir ~/.ccache
          cp .github/workflows/ccache.conf ~/.ccache/ccache.conf
      - name: Cache llvm
        uses: actions/cache@v2
        id: cache-llvm
        with:
          path: |
            deps/llvm/osx-X86_64/include
            deps/llvm/osx-X86_64/lib
          key: llvm-${{ runner.os }}-osx-X86_64-${{ hashFiles('deps/llvm/build.py') }}-${{ env.MACOSX_DEPLOYMENT_TARGET }}
      - name: build llvm
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          python3 ./deps/llvm/build.py prepare ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py build   ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py package ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py clean   ${QBDI_PLATFORM}-${QBDI_ARCH}

  build-pyqbdi:
    needs: build-llvm
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    env:
      QBDI_PLATFORM: 'osx'
      QBDI_ARCH: 'X86_64'
      MACOSX_DEPLOYMENT_TARGET: '10.14'
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          brew install cmake ninja ccache
          python3 -m pip install --upgrade pip setuptools wheel
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache ccache
        uses: actions/cache@v2
        id: cache-ccache-python
        with:
          path: |
            ~/.ccache
          key: ccache-osx-X86_64-${{ hashFiles('.github/workflows/ccache.conf') }}-python-${{ matrix.python-version }}
          restore-keys: |
            ccache-osx-X86_64-${{ hashFiles('.github/workflows/ccache.conf') }}
      - if: steps.cache-ccache-python.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.ccache
          cp .github/workflows/ccache.conf ~/.ccache/ccache.conf
      - name: Cache llvm
        uses: actions/cache@v2
        id: cache-llvm-python
        with:
          path: |
            deps/llvm/osx-X86_64/include
            deps/llvm/osx-X86_64/lib
          key: llvm-${{ runner.os }}-osx-X86_64-${{ hashFiles('deps/llvm/build.py') }}-${{ env.MACOSX_DEPLOYMENT_TARGET }}-python-${{ matrix.python-version }}
          restore-keys: |
            llvm-${{ runner.os }}-osx-X86_64-${{ hashFiles('deps/llvm/build.py') }}-${{ env.MACOSX_DEPLOYMENT_TARGET }}
      - name: build llvm
        if: steps.cache-llvm-python.outputs.cache-hit != 'true'
        run: |
          [[ ! -d ./deps/llvm/osx-X86_64 ]] || exit 0
          python3 ./deps/llvm/build.py prepare ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py build   ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py package ${QBDI_PLATFORM}-${QBDI_ARCH}
          python3 ./deps/llvm/build.py clean   ${QBDI_PLATFORM}-${QBDI_ARCH}
      - run: mkdir -p build
      - name: Build PyQBDI ${{ matrix.python-version }}
        run: |
          python3 --version
          python3 setup.py bdist_wheel
      - name: Export package
        uses: actions/upload-artifact@v2
        with:
          name: PyQBDI OSX X86_64 ${{ matrix.python-version }}
          path: dist/*
